### ISSUE TITLE
Failed to set up. 

### ISSUE THREAD

**Issue by JohnnyCarcinogen** [MTrab/landroid_cloud#391] opened 2023-06-06 15:48 UTC
### Describe the issue

I thought this might initially due to the device not showing online because of the FML module, but I e removed that. Disconnected the Landroid from My Landroids online, and reconnected. It’s shows online now, but I continue to get the errors below. 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206 
Integration: Landroid Cloud (documentation, issues) 
First occurred: June 4, 2023 at 4:44:58 PM (3 occurrences) 
Last logged: 11:39:42 AM

Error setting up entry Worx - REDACTED@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 597, in _fetch
    device = DeviceHandler(self._api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 46, in __init__
    self.__mapinfo(api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 100, in __mapinfo
    self.zone = Zone(data)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 50, in __init__
    self["current"] = self["indicies"][self["index"]]
TypeError: list indices must be integers or slices, not NoneType

AND

This error originated from a custom integration.

Logger: custom_components.landroid_cloud.config_flow
Source: custom_components/landroid_cloud/utils/logger.py:116 
Integration: Landroid Cloud (documentation, issues) 
First occurred: June 4, 2023 at 4:44:49 PM (1 occurrences) 
Last logged: June 4, 2023 at 4:44:49 PM

(Config, Import) Landroid_cloud configuration for REDACTED@gmail.com already imported, you can safely remove the entry from your configuration.yaml as this is no longer used

### What version of Home Assistant Core has the issue?

2023.5.4

### What version of the Landroid Cloud integration do you have installed

3.0.3

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid WR155

### Diagnostics information (NOT log entries!)

N/A

### Relevant log entries

```txt
See above
```

**Comment by MTrab** [comment] 2023-06-08 18:01
Duplicate of https://github.com/MTrab/landroid_cloud/issues/389

**Closed by MTrab** 2023-06-08 18:01 UTC
Labels: bug

**Comment by JohnnyCarcinogen** [comment] 2023-06-09 22:39
It’s working again. Thank you so much. Going to do the sponsor thing or something.
