### ISSUE TITLE
Error setting up entry Worx - [MyEmail]@gmail.com for landroid_cloud

### ISSUE THREAD

**Issue by benvoi** [MTrab/landroid_cloud#312] opened 2023-04-03 11:54 UTC
### Describe the issue

Downloaded Landroid Cloud from HACS and received the following error while loading the service:

> 2023-04-03 13:47:49.642 INFO (MainThread) [homeassistant.setup] Setting up landroid_cloud
2023-04-03 13:47:49.644 INFO (MainThread) [homeassistant.setup] Setup of domain landroid_cloud took 0.0 seconds
2023-04-03 13:47:49.761 INFO (MainThread) [custom_components.landroid_cloud]
https://github.com/mtrab/landroid_cloud/issues
2023-04-03 13:47:49.769 DEBUG (MainThread) [custom_components.landroid_cloud] (Setup) Opening connection to Worx account for [MyEmail]@gmail.com
2023-04-03 13:47:54.896 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - [MyEmail]@gmail.com for landroid_cloud
File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

None

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_2023-04-03T11-53-54.443Z.log](https://github.com/MTrab/landroid_cloud/files/11137931/home-assistant_2023-04-03T11-53-54.443Z.log)

**Comment by MTrab** [comment] 2023-04-03 11:56
Duplicate of #282

**Closed by MTrab** 2023-04-03 11:56 UTC
Labels: bug
