### ISSUE TITLE
Error when reloading the integration causes the integration to fully crash

### ISSUE THREAD

**Issue by prof7bit** [MTrab/landroid_cloud#347] opened 2023-04-21 08:03 UTC
### Describe the issue

In previous versions, when it lost connection, I could simply reload the integration and it reconnected. Since the connection problem (although greatly improved) still happens at least once a day, I still need to reload the extension occasionally. But now suddenly it always demands a complete home assistant restart.

Is this really necessary?

### What version of Home Assistant Core has the issue?

core- 2023.4.5

### What version of the Landroid Cloud integration do you have installed

3.0.b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR167E

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
-
```

**Comment by MTrab** [comment] 2023-04-21 08:05
Duplicate of #341

**Comment by prof7bit** [comment] 2023-04-21 08:12
How is this a duplicate of "mower stopped updating"?

This is about it forcing me to reboot after reload, which was previously not needed.

**Comment by MTrab** [comment] 2023-04-21 08:13
From that very little information given, I see it as the same

**Comment by prof7bit** [comment] 2023-04-21 08:15
The title of the bug IMHO clearly describes the issue.

**Comment by MTrab** [comment] 2023-04-21 08:16
And yet no diagnostics or logs - how am I supposed to interpret anything from nothing?

**Comment by prof7bit** [comment] 2023-04-21 08:21
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 81, in async_unload_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 219, in disconnect
    self.mqtt.disconnect()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 222, in disconnect
    self.client.unsubscribe(self._topic.pop(topic))
TypeError: 'str' object cannot be interpreted as an intege

**Comment by MTrab** [comment] 2023-04-21 08:22
Much better - ALWAYS provide the requested info

**Comment by prof7bit** [comment] 2023-04-21 08:25
Sorry,

I assumed you accidentally changed some property of the integration (if there even is such a thing) to now always require reboot after reload. So i implicitly thought you would immediately know what I am talking about.

It did not even for a second come to my mind that there would be a traceback in the log for this.

**Comment by MTrab** [comment] 2023-04-21 08:27
There is no such option to require a reboot, as that's against design strategies.

But I do think I know what's causing that issue though and it will be fixed befor the integration goes out of beta again.

**Comment by prof7bit** [comment] 2023-04-21 08:33
So then maybe it could also should be filed as an issue against home assistant itself to clearly indicate tn the "restart required" popup that an error has happened, instead of just saying a reboot is needed, as if it were part of the normal procedure.

**Comment by Cosmicbase** [comment] 2023-04-21 08:36
@MTrab 
I think he means the same as me.
After restarting the integration, there is a crash. The "Reload", "Rename" and "diagnostic info" button is no longer available.
Maybe he means the same thing as me or the other way around.

![Unbenannt](https://user-images.githubusercontent.com/31271212/233588146-49959b7b-c490-4c38-8173-2a5a86f1d76d.PNG)

**Comment by MTrab** [comment] 2023-04-21 08:38
> @MTrab I think he means the same as me. After restarting the integration, there is a crash. The "Reload", "Rename" and "diagnostic info" button is no longer available. Maybe he means the same thing as me or the other way around.

Could be - again, you didn't provide any diagnostics or error logs as well. ALWAYS ALWAYS ALWAYS provide the requested info in the issues, make debugging _SO_ much more easy.

**Comment by Cosmicbase** [comment] 2023-04-21 08:40
diagnostics info after restart not longer visible, only debug.

**Comment by MTrab** [comment] 2023-04-21 08:41
And I guess logs as well ;)

**Comment by Cosmicbase** [comment] 2023-04-21 08:46
Here is the log.

[home-assistant_landroid_cloud_2023-04-21T08-43-22.546Z.log](https://github.com/MTrab/landroid_cloud/files/11294034/home-assistant_landroid_cloud_2023-04-21T08-43-22.546Z.log)

**Comment by MTrab** [comment] 2023-04-21 08:49
Exactly the same as in this issue - would have been nice to have when you created your issue.

**Comment by Cosmicbase** [comment] 2023-04-21 08:50
Ok I'll do better next time.

**Comment by MTrab** [comment] 2023-04-21 08:51
Guess I'll just need to enforce the fact that if info is missing in the issues I'll just go and close them

**Comment by MTrab** [comment] 2023-05-16 06:59
Will be fixed on next release, as this is related to this pull in pyworxcloud: https://github.com/MTrab/pyworxcloud/pull/136

**Closed** 2023-05-16 18:32 UTC
Labels: bug, fixed, pyworxcloud
