### ISSUE TITLE
The requested zone is not defined - 3.0.1

### ISSUE THREAD

**Issue by wizu** [MTrab/landroid_cloud#378] opened 2023-05-24 12:42 UTC
### Describe the issue

At version 3.0.1 of landroid_cloud set zone is not working. At 3.0.0 it was working great.

### What version of Home Assistant Core has the issue?

2023.5.4

### What was the last working version of Home Assistant Core?

2023.5.4

### What version of the Landroid Cloud integration do you have installed

3.0.1

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR147E.1

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-7ba6b6f47f3f6d2622b36547c680474e.json.txt](https://github.com/MTrab/landroid_cloud/files/11554638/config_entry-landroid_cloud-7ba6b6f47f3f6d2622b36547c680474e.json.txt)

### Relevant log entries

```txt
2023-05-24 14:14:39.594 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140386768608832] The requested zone is not defined
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/landroid_cloud/services.py", line 146, in async_call_landroid_service
await api.services[service][ATTR_SERVICE](service_data)
File "/config/custom_components/landroid_cloud/device_base.py", line 727, in async_set_zone
raise HomeAssistantError("The requested zone is not defined") from None
homeassistant.exceptions.HomeAssistantError: The requested zone is not defined
```

**Comment by MTrab** [comment] 2023-05-25 11:03
That seems strange. Nothing have been changed for that service call between the 2 releases.

I see you only have 2 zones defined - it's not because you are trying to request one of the undefined zones, right?!

**Comment by wizu** [comment] 2023-05-25 11:05
No, I try to change from zone 2 to zone 1. Right now I'm on 3.0.0 and it works ok.

**Comment by MTrab** [comment] 2023-05-25 11:07
Strange - would you mind sharing your credentials at landroid_cloud (at) trab.dk adding the text Issue 378 to the subject.
Then I'll test and see what's going on, as I can't reproduce this myself (don't use zones in any of my setups right now)

**Comment by wizu** [comment] 2023-05-25 11:09
Sure, I will do that when I'll be at home.

**Comment by wizu** [comment] 2023-05-26 08:32
@MTrab I've send you the credentials.

**Comment by MTrab** [comment] 2023-05-26 09:22
Perfect - I'll take a look after lunch. If it's a quick fix I'll let the next release await this fix.

**Comment by MTrab** [comment] 2023-05-26 11:02
Fixed in next release

**Closed** 2023-05-26 11:04 UTC
Labels: bug
