### ISSUE TITLE
Landroid app and services out of function.

### ISSUE THREAD

**Issue by MadsBekker** [MTrab/landroid_cloud#28] opened 2020-05-05 18:13 UTC
Hi. 

This is my first thread on github, so please excuse me if i write something in a wrong location.

I have installed the plugin to Home Assistant.
Everything seems to work fine in the beginning, but all of the sudden my app does not work. I can read into from the landroid - but no communication to the landroid (start/pause, change schedule. Edit rain delay ect.).

Neither does the services from Home Assistant work any longer. 
The only way I can control the robot now, is at its own panel on top. 

I have tried the following:
1. Install an older firmware to the landroid robot by USB.
2. Make a new json file from worx website with Wi-Fi credentials to transfer by USB.
3. Remove, re-install the plugin.
4. Restart everything without the Home Assistant turned on.

Found an issue in the link below that seems to be the exact same problem. Using Google translate to Eng. makes the text understandable (but all this programming-language is still confusing for a humble electrician as I am).
https://easydomoticz.com/forum/viewtopic.php?p=82426

I did not make any significant changes when these problems came up, but still you can have my info here:
Home Assistant on rpi - vers. 0.109.4
Landroid firmware: 3.08
Landroid model: WR142e

Hope I have the info you need. As programming is not an area I know much of, I am not sure what information is relevant for this to be solved. 

Landroid is not mentioned in the log, besides "2020-05-05 20:03:40 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant."

If not please let me know is you need further info.
Mads. Denmark.

**Comment by dheuts90** [comment] 2020-05-05 18:53
I had the same problem. Seemed my Worx cloud account was banned for 24 hrs because of using unofficial app. I solved it by transferring my Landroid to another emailadress worx account. Good luck!

**Comment by MadsBekker** [comment] 2020-05-05 19:57
Great. Never thought of that was the reason. 
Did you add the plugin to the new account as well (if so, how does it work?) - or did you just accepted that this plugin was not usable?

**Comment by MTrab** [comment] 2020-05-05 19:59
There was a bug n an earlier version that refreshed WAY to often, that might have had something to say.

That's fixed thoua few versions back, so shouldn't be a problem anymore.

**Comment by Barma-lej** [comment] 2020-05-05 20:07
I had the same probleme too. I unlink(ed) Landroid from my account here: [My Landroids](https://account.worxlandroid.com/product-items) , then i has added landroid in app and it works again.

**Comment by MTrab** [comment] 2020-05-05 20:08
> I had the same probleme too. I unlink(ed) Landroid from my account here: [My Landroids](https://account.worxlandroid.com/product-items) , then i has added landroid in app and it works again.

Did you add to the same account as you unlinked it from?

**Comment by Barma-lej** [comment] 2020-05-05 20:14
Yes, the same. And it is already second time :)
Thank you for your work, have you any plans to add a scheduler und rain delay?

**Comment by MTrab** [comment] 2020-05-05 20:15
Yes - currently I'm banned myself, so right now nothing happes development wise :D 
Might try this "fix" tomorrow thou.

**Comment by MadsBekker** [comment] 2020-05-05 20:22
Couldn't help myself. Had to leave my Netflix movie, and go out in the dark garden to try with a new account (not easy to scan the QR of the robot in the dark 🙂).

I can confirm that it worked with a completely new account.
For future readers:
1. Unlink the robot from the "broken" account.
2. Create a new account (might be possible to reuse the same, as Barma-lej describes
3. Add the robot to the new account. 

Thank you so much for your help in this. 
Best regards.

**Closed** 2020-05-05 20:22 UTC

**Comment by MTrab** [comment] 2020-05-06 10:59
I can confirm it's working after unlinking from the webpage and adding in app :) Super nice, then I can move forward in developing this intragration.

Thank you for the tip, Barma-lej :)
Think I'll be adding a note or known bugs section, with this tip, in the README :)

**Comment by rosscullen** [comment] 2020-05-06 12:58
> Couldn't help myself. Had to leave my Netflix movie, and go out in the dark garden to try with a new account (not easy to scan the QR of the robot in the dark 🙂).
> 
> I can confirm that it worked with a completely new account.
> For future readers:
> 
> 1. Unlink the robot from the "broken" account.
> 2. Create a new account (might be possible to reuse the same, as Barma-lej describes
> 3. Add the robot to the new account.
> 
> Thank you so much for your help in this.
> Best regards.

Thanks @MTrab @Barma-lej and others for this. My Landroid was partually blocked in that I could get status but wasnt able to issue remote commands from app or Landroid_bridge or Landroid_cloud (such as start/stop). I followed the instructions above (deleted/re-added) and it worked perfectly. Much appreciated :-D
