### ISSUE TITLE
Integration doesen't start after upgrading Homeassistant to 2023.8.4

### ISSUE THREAD

**Issue by arcano81** [MTrab/landroid_cloud#423] opened 2023-08-31 07:00 UTC
### Describe the issue

After upgrading Homeassistant OS to 2023.8.4 the integration doesn't start any more. (Configuration didn't succeeded)
![image](https://github.com/MTrab/landroid_cloud/assets/76391221/787d1b0d-3a86-4d84-b601-d98e520fda40)

### What version of Home Assistant Core has the issue?

core-2023.8.4

### What was the last working version of Home Assistant Core?

core-2023.8.3

### What version of the Landroid Cloud integration do you have installed

3.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR130E and WR167E

### Diagnostics information (NOT log entries!)

NONE, the integration doesn't allow downloading diagnostics data

### Relevant log entries

```txt
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206
Integration: Landroid Cloud (documentation, issues)
First occurred: 08:07:16 (2 occurrences)
Last logged: 08:38:50

Error setting up entry Worx - xxx.yyy@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 611, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/api.py", line 119, in get_mowers
    mower["firmware_version"] = "{:.2f}".format(mower["firmware_version"])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by MTrab** [comment] 2023-08-31 07:01
Duplicate of https://github.com/MTrab/landroid_cloud/issues/417

**Closed by MTrab** 2023-08-31 07:01 UTC
Labels: bug
