### ISSUE TITLE
torgue entity missing after v5.0.2

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#726] opened 2024-11-06 09:45 UTC
### Describe the issue

I've been missing the drive torque entity since version 5.0.2.
However, the drive torque can be changed and set in MQTT using the Desk app.
Can you implement the entity again?

![torque](https://github.com/user-attachments/assets/7dcab974-32f3-494f-872a-4dcd3d2b5c90)

![toadie](https://github.com/user-attachments/assets/2211a31e-598a-44a8-bb3d-0a44c71353ac)

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

2024.10.4

### What version of the Landroid Cloud integration do you have installed

v5.1.0

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500 (WR141E) Firmware: 3.30

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-5347425cf0463f06f31bed7b9f902102.json](https://github.com/user-attachments/files/17645014/config_entry-landroid_cloud-5347425cf0463f06f31bed7b9f902102.json)

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment] 2024-11-06 09:47
Duplicate of #620

**Closed by MTrab** 2024-11-06 09:47 UTC
Labels: bug
