### ISSUE TITLE
[FR]: show correct zone in status

### ISSUE THREAD

**Issue by cm86** [MTrab/landroid_cloud#530] opened 2024-03-19 20:41 UTC
### Describe the feature you wish to make a request for

Hello, is it possible to show the right zone in the infos...?

Mower: Kress RTK

As you can see here in the picture, it shows "Zone 1"
![Bildschirmfoto 2024-03-19 um 21 36 28](https://github.com/MTrab/landroid_cloud/assets/14919688/ce091ea8-d046-4162-a40c-7d4b378fe6f3)

And again, no information about which zone is currently being mowed can be found in the attributes of the entity...

![Bildschirmfoto 2024-03-19 um 21 37 22](https://github.com/MTrab/landroid_cloud/assets/14919688/7d3ae380-c1c7-4893-9e41-513ec64e6a03)

**Comment by MTrab** [comment] 2024-03-20 07:25
Duplicate of #521 as far as I can see

**Closed by MTrab** 2024-03-20 07:25 UTC
Labels: feature request
