### ISSUE TITLE
Home Assistant freezes after update to 2.2.0 on start when mower is offline

### ISSUE THREAD

**Issue by JurajNyiri** [MTrab/landroid_cloud#199] opened 2022-07-12 11:17 UTC
### Environment:
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest

## Configuration

N/A

## Describe the bug
After updating to 2.2.0 from 2.0.3 my Home Assistant instance freezes after a couple of seconds after seemingly random time, every time after reboot after like 30 - 60 seconds.

There are 2 different behaviours on my instance;

With https://github.com/StyraHem/ShellyForHASS installed, I get logs spammed by blocking events from pyShelly and it gets frozen (while spamming error log).

Without https://github.com/StyraHem/ShellyForHASS installed, there is nothing significant in the logs, they just stop populating. Supervisor is saying that it cannot restart because tasks are running but core is not doing anything, no logs no significant error.

I pinpointed issue to being with landroid_cloud by removing it via ssh and restarting host - Home Assistant booted up without any issues. Then I reinstalled ShellyForHass and again, no issues.

I understand this will be very hard to debug, so hopefully some users that are also experiencing this will be able to provide more details. Let me know how I can help.

## Debug log

N/A

**Comment by ToCloneOrNotToClone** [comment] 2022-07-12 20:19
I have similar issue. Had to remove landroid_cloud component to get it fully started up.

**Comment by rosscullen** [comment] 2022-07-12 20:27
Been having issues myself recently but not sure it's related. Home Assistant stopping on startup but nothing specific to Landroid Cloud in logs... not fully sure its related but its the only integration that ive updated (other than HA Core) that's had a major update. Had logged a HA ticket but closed it because of no response. See https://github.com/home-assistant/core/issues/74538

**Comment by MTrab** [comment] 2022-07-13 06:51
Any specific actions prior to the Home Assistant freezes? (Trying to recreate the issue without any luck)

**Comment by JurajNyiri** [comment] 2022-07-13 08:34
None, just update and restart.

**Comment by ToCloneOrNotToClone** [comment] 2022-07-13 09:55
I tried enabling debug logging. This is the output from ha core logs. I tried multiple version and now they all seem to do the same. It will only start up if I remove the landdroid_cloud component

2022-07-13 11:44:06 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new vacuum.landroid_cloud entity: vacuum.baghaven
2022-07-13 11:44:06 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event entity_registry_updated[L]: action=create, entity_id=vacuum.baghaven>
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Update signal) Updating
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Update signal) Online: False
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Update signal) State 'offline'
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Update signal) Attributes:
{'accessories': None, 'battery': {'cycles': {'total': 0, 'current': 0, 'reset_at': None, 'reset_time': None}}, 'blades': {'total_on': None, 'reset_at': None, 'reset_time': None, 'current_on': None}, 'error': {'id': -1, 'description': 'unknown'}, 'firmware': {'auto_upgrade': True, 'version': 3.52}, 'locked': False, 'mac_address': 'xxxxxx', 'model': 'Landroid S500', 'online': False, 'orientation': {'pitch': 0, 'roll': 0, 'yaw': 0}, 'rain_sensor': {'delay': 0}, 'schedule': {'time_extension': 0, 'active': True, 'auto_schedule': {'settings': {}, 'enabled': None}}, 'serial_number': 'xxxxx', 'status_info': {'id': -1, 'description': 'unknown'}, 'time_zone': 'Europe/Copenhagen', 'zone': {'current': None, 'index': None, 'indicies': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'starting_point': [0, 0, 0, 0]}, 'capabilities': None, 'mqtt_connected': True, 'supported_landroid_features': 0}
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Setup) Connecting to dispatcher signal 'landroid_cloud_update_baghaven'
2022-07-13 11:44:06 DEBUG (MainThread) [custom_components.landroid_cloud.device_base] (Baghaven, Setup) Features not assessed, calling assessment with base features at 4671
2022-07-13 11:45:04 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:45:04 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:46:05 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:46:05 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:47:05 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:47:05 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:48:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:48:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:49:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:49:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.mqtt.message_received] Received MQTT message for WR105SI - processing data {"cfg":{"id":0,"lg":"it","tm":"11:49:51","dt":"13/07/2022","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"30173704170204040111"},"dat":{"mac":"F0FE6B205B86","fw":3.52,"bt":{"t":31.6,"v":17.63,"p":33,"nr":7790,"c":0,"m":0},"dmp":[-0.7,0.4,309.6],"st":{"b":42612,"d":727085,"wt":45901},"ls":7,"le":0,"lz":0,"rsi":-83,"lk":0}}
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.decode_data] Data decoding for WR105SI started
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.decode_data] Found JSON decoded data: {'cfg': {'id': 0, 'lg': 'it', 'tm': '11:49:51', 'dt': '13/07/2022', 'sc': {'m': 1, 'p': 0, 'd': [['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]]}, 'cmd': 0, 'mz': [0, 0, 0, 0], 'mzv': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'rd': 0, 'sn': 'xxxx'}, 'dat': {'mac': 'xxxx', 'fw': 3.52, 'bt': {'t': 31.6, 'v': 17.63, 'p': 33, 'nr': 7790, 'c': 0, 'm': 0}, 'dmp': [-0.7, 0.4, 309.6], 'st': {'b': 42612, 'd': 727085, 'wt': 45901}, 'ls': 7, 'le': 0, 'lz': 0, 'rsi': -83, 'lk': 0}}
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.decode_data] Data for WR105SI was decoded
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.events] Checking ['name'] against {'name': 'WR105SI', 'device': {}}
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [pyworxcloud.events] Checking ['device'] against {'name': 'WR105SI', 'device': {}}
2022-07-13 11:49:52 DEBUG (Thread-3 (_thread_main)) [custom_components.landroid_cloud.api] (WR105SI, Update signal) Received new data from API to WR105SI, dispatching landroid_cloud_update_wr105si
2022-07-13 11:50:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:50:06 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP
2022-07-13 11:51:07 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Sending PINGREQ
2022-07-13 11:51:07 DEBUG (Thread-4 (_thread_main)) [paho.mqtt.client] Received PINGRESP

**Comment by MTrab** [comment] 2022-07-13 12:15
OH! Wait a minute!

Disabled some checks, and the one device that makes this hang is one that is currently offline.
Shouldn't happen thou, but could you please check if the mowers is actually reachable?

**Comment by JurajNyiri** [comment] 2022-07-13 12:46
Yes it was offline when I was trying to update! It always gets stuck on dogs toys 🤦

**Comment by rjwonder** [comment] 2022-07-13 15:11
It looks like you already found the reason, but I can confirm that while my landroid was off, HA could not restart. When I switched it back on it started right away

`2022-07-13T14:56:14.849284771Z 2022-07-13 16:56:14 WARNING (MainThread) [custom_components.landroid_cloud.device_base] (Mower, Update signal) MQTT connection is offline, scheduling Web API refresh in 15 minutes. Device is in readonly mode!
2022-07-13T15:02:52.646352360Z 2022-07-13 17:02:52 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform landroid_cloud is taking over 10 seconds.
2022-07-13T15:02:52.748708239Z 2022-07-13 17:02:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
2022-07-13T15:02:52.748733309Z Traceback (most recent call last):
2022-07-13T15:02:52.748741383Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
2022-07-13T15:02:52.748745671Z     await self._send_frame(message, WSMsgType.PING)
2022-07-13T15:02:52.748752063Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
2022-07-13T15:02:52.748755882Z     self._write(header + mask + message)
2022-07-13T15:02:52.748759551Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
2022-07-13T15:02:52.748763323Z     raise ConnectionResetError("Cannot write to closing transport")
`

**Comment by rosscullen** [comment] 2022-07-13 18:01
Come to think of it, my WiFi outdoor shuts off from 21:00 to 06:30... I had done a HA reboot at night and it didn't come back up... but it came back online the next morning... so that sounds very possible. Thanks as ever @MTrab

**Comment by jcustenborder** [comment] 2022-07-13 18:15
@MTrab I ran into this problem as well. You're welcome to use my account again for testing.

**Comment by rosscullen** [comment] 2022-07-13 21:10
> Come to think of it, my WiFi outdoor shuts off from 21:00 to 06:30... I had done a HA reboot at night and it didn't come back up... but it came back online the next morning... so that sounds very possible. Thanks as ever @MTrab 

Did some testing there and I can confirm same issue (HA won't fully restart until landroid device is online).

**Closed** 2022-07-15 06:08 UTC
Labels: bug, high priority, in progress, patch
